### ISSUE TITLE
Links Posted on Twitter include rest of timeline

### ISSUE THREAD

**Issue by marudor** [sisch/realitycheck#1]
The links posted on twitter should not only show the posted entry but also the rest below.
So the post associated to the link should be pinned on top - then your normal flow of posts below it excluding the one pinned.
That way someone can read the posted one as well as read the others without explicitly going back to home.

**Comment by sisch** [comment]
The blog now shows one entry specified by the URI call and all other (excluding the former one) posts sorted by date below.
