### ISSUE TITLE
Twitter-Integration

### ISSUE THREAD

**Issue by Maddosaurus** [sisch/realitycheck#4]
Ohai!

Vorschlag für rc.pl: Twitter-Integration.
Mein spontaner Vorschlag wäre es, eine Funktion einzuführen, die z.B. neben dem Flattr-Button platz hätte (jupp, pro Eintrag einer).
Klickt man sie, wird mit dem eigenen Account ein entsprechender Tweet abgesetzt.
Eventuell mit dem Titel des jeweiligen Eintrages und, falls platz, vielleicht den ersten Worten.

Die Frage ist eher, ob man das mit dem offiziellen Twitter-Button löst, da ich irgendwo im Hinterkopf habe, dass da Datenschutzbedenken waren. Im Großen und Ganzen ginge der Vorschlag aber in die Richtung, was auch Portale wie imgur, 9gag und co anbieten.

**Comment by sisch** [comment]
Die Funktion einzelne Posts zu vertwittern ist jetzt da. Ich bin noch unschlüssig, ob der Standardtext nervig oder sinnvoll ist.
